begin;

create extension if not exists pgtap with schema extensions;
select plan(74);

select has_table('public', 'fila_espera', 'fila de espera existe');
select has_table('public', 'notificacoes', 'fila de notificações existe');
select has_table('public', 'push_subscriptions', 'assinaturas push existem');
select has_table('public', 'telemetria_eventos', 'telemetria existe');
select has_table('public', 'booking_intents', 'intenções temporárias existem');
select has_table('public', 'api_rate_limits', 'limites de API existem');
select has_table('public', 'avaliacoes', 'avaliações existem');
select has_table('public', 'admin_audit_logs', 'auditoria administrativa existe');
select has_table('public', 'configuracoes_plataforma', 'configurações globais existem');
select has_table('public', 'terminais_pagamento', 'cadastro de maquininhas existe');
select has_table('public', 'planos_mensais', 'planos mensais existem');
select has_table('public', 'assinaturas_clientes', 'assinaturas de clientes existem');
select has_table('public', 'movimentacoes_financeiras', 'movimentações financeiras existem');
select has_table('public', 'checkouts_pagamento', 'checkouts online existem');
select has_column('public', 'agendamentos', 'pagamento_online_status', 'agendamento registra pagamento online');
select has_column('public', 'barbeiros', 'funcao', 'profissional distingue proprietário e funcionário');
select has_column('public', 'barbeiros', 'comissao_percentual', 'profissional possui comissão configurável');
select has_column('public', 'barbeiros', 'observacoes_gestao', 'gestão possui observações internas');

select ok((select relrowsecurity from pg_class where oid = 'public.fila_espera'::regclass), 'RLS ativo na fila de espera');
select ok((select relrowsecurity from pg_class where oid = 'public.notificacoes'::regclass), 'RLS ativo nas notificações');
select ok((select relrowsecurity from pg_class where oid = 'public.push_subscriptions'::regclass), 'RLS ativo nas assinaturas push');
select ok((select relrowsecurity from pg_class where oid = 'public.telemetria_eventos'::regclass), 'RLS ativo na telemetria');
select ok((select relrowsecurity from pg_class where oid = 'public.booking_intents'::regclass), 'RLS ativo nas intenções temporárias');
select ok((select relrowsecurity from pg_class where oid = 'public.api_rate_limits'::regclass), 'RLS ativo nos limites de API');
select ok((select relrowsecurity from pg_class where oid = 'public.avaliacoes'::regclass), 'RLS ativo nas avaliações');
select ok((select relrowsecurity from pg_class where oid = 'public.admin_audit_logs'::regclass), 'RLS ativo na auditoria administrativa');
select ok((select relrowsecurity from pg_class where oid = 'public.configuracoes_plataforma'::regclass), 'RLS ativo nas configurações globais');
select ok((select relrowsecurity from pg_class where oid = 'public.terminais_pagamento'::regclass), 'RLS ativo nas maquininhas');
select ok((select relrowsecurity from pg_class where oid = 'public.planos_mensais'::regclass), 'RLS ativo nos planos');
select ok((select relrowsecurity from pg_class where oid = 'public.assinaturas_clientes'::regclass), 'RLS ativo nas assinaturas');
select ok((select relrowsecurity from pg_class where oid = 'public.movimentacoes_financeiras'::regclass), 'RLS ativo no financeiro');
select ok((select relrowsecurity from pg_class where oid = 'public.checkouts_pagamento'::regclass), 'RLS ativo nos checkouts');

select has_function('public', 'eh_admin_global', array[]::text[], 'verificação administrativa global existe');
select has_function('public', 'obter_resumo_admin', array[]::text[], 'resumo administrativo existe');
select has_function('public', 'listar_usuarios_admin', array['text', 'text', 'integer'], 'diretório administrativo existe');
select has_function('public', 'obter_configuracao_publica', array[]::text[], 'configuração pública segura existe');
select has_function('public', 'listar_estabelecimentos_publicos', array[]::text[], 'descoberta pública de estabelecimentos existe');
select has_function('public', 'admin_atualizar_tipo_usuario', array['uuid', 'text'], 'gestão administrativa de perfis existe');
select has_function('public', 'registrar_movimentacao_financeira', array['uuid', 'bigint', 'text', 'text', 'text', 'numeric', 'numeric', 'text', 'text'], 'registro financeiro protegido existe');
select has_function('public', 'obter_resumo_financeiro', array['uuid', 'date', 'date'], 'resumo financeiro protegido existe');
select has_function('public', 'listar_equipe_barbearia', array['uuid'], 'listagem de equipe protegida existe');
select has_function('public', 'atualizar_dados_profissional', array['bigint', 'text', 'text', 'numeric', 'text'], 'gestão de comissão existe');
select has_function('public', 'definir_proprietario_barbearia', array['uuid', 'bigint'], 'atribuição operacional de proprietário existe');
select has_function('public', 'definir_feriado_fechado', array['uuid', 'date', 'text'], 'decisão de fechar no feriado existe');
select has_function('public', 'definir_feriado_aberto', array['uuid', 'date'], 'decisão de abrir no feriado existe');

select hasnt_function('public', 'obter_catalogo_publico', array[]::text[], 'sobrecarga global legada do catálogo foi removida');
select ok(has_function_privilege('anon', 'public.obter_catalogo_publico(text)', 'execute'), 'anon consulta apenas catálogo identificado por estabelecimento');
select ok(has_function_privilege('anon', 'public.listar_estabelecimentos_publicos()', 'execute'), 'anon pode escolher um estabelecimento público');
select ok(has_function_privilege('anon', 'public.obter_configuracao_publica()', 'execute'), 'anon pode ler somente a configuração pública');
select ok(has_function_privilege('anon', 'public.listar_planos_publicos(text)', 'execute'), 'anon pode consultar planos mensais ativos');
select ok(has_function_privilege('anon', 'public.buscar_horarios_disponiveis(bigint,bigint,date)', 'execute'), 'anon pode consultar disponibilidade');
select ok(not has_function_privilege('anon', 'public.criar_agendamento_com_origem(bigint,bigint,date,time,text)', 'execute'), 'anon não cria agendamento sem autenticação');
select ok(not has_function_privilege('anon', 'public.atualizar_configuracoes_avancadas(text,boolean,smallint,numeric,text,text,boolean,boolean,boolean,smallint,smallint)', 'execute'), 'anon não altera regras do negócio');
select ok(not has_table_privilege('anon', 'public.booking_intents', 'select'), 'anon não lê intenções com dados pessoais');
select ok(not has_function_privilege('anon', 'public.consume_api_rate_limit(text,integer,integer)', 'execute'), 'anon não manipula limites da API');
select ok(not has_function_privilege('anon', 'public.claim_due_notifications(integer,uuid,integer)', 'execute'), 'anon não reivindica a fila de mensagens');
select ok(not has_function_privilege('anon', 'public.cleanup_operational_data()', 'execute'), 'anon não executa limpeza operacional');
select ok(not has_function_privilege('anon', 'public.atualizar_informacoes_legais(text,text,text,smallint)', 'execute'), 'anon não altera informações legais');
select ok(has_function_privilege('anon', 'public.obter_informacoes_legais_barbearia(text)', 'execute'), 'anon consulta identificação legal da unidade pública');
select ok(not has_function_privilege('authenticated', 'public.atualizar_informacoes_legais(text,text,text,smallint)', 'execute'), 'atualização legal global legada permanece bloqueada');
select ok(not has_table_privilege('anon', 'public.terminais_pagamento', 'select'), 'anon não lê dados de maquininhas');
select ok(not has_table_privilege('anon', 'public.assinaturas_clientes', 'select'), 'anon não lê assinaturas de clientes');
select ok(not has_table_privilege('anon', 'public.movimentacoes_financeiras', 'select'), 'anon não lê o caixa');
select ok(not has_table_privilege('anon', 'public.checkouts_pagamento', 'select'), 'anon não lê checkouts de pagamento');
select ok(not has_table_privilege('authenticated', 'public.push_subscriptions', 'select'), 'versão web não expõe assinaturas push legadas');
select ok(not has_table_privilege('authenticated', 'public.configuracoes_negocio', 'update'), 'configuração global legada permanece somente leitura');
select ok(not has_function_privilege('anon', 'public.admin_atualizar_tipo_usuario(uuid,text)', 'execute'), 'anon não altera perfis');
select ok(not has_function_privilege('anon', 'public.registrar_movimentacao_financeira(uuid,bigint,text,text,text,numeric,numeric,text,text)', 'execute'), 'anon não registra movimentações');
select ok(not has_function_privilege('anon', 'public.listar_equipe_barbearia(uuid)', 'execute'), 'anon não consulta equipe interna');
select ok(not has_function_privilege('anon', 'public.atualizar_dados_profissional(bigint,text,text,numeric,text)', 'execute'), 'anon não altera comissão de profissional');
select ok(not has_function_privilege('authenticated', 'public.criar_minha_barbearia(text,text,boolean)', 'execute'), 'proprietário não cria unidade sem a plataforma');
select ok(not has_function_privilege('authenticated', 'public.admin_atribuir_proprietario_barbearia(uuid,uuid)', 'execute'), 'atribuição legada de proprietário permanece revogada');
select ok(position('p_tipo not in (''cliente'', ''barbeiro'', ''admin'')' in pg_get_functiondef('public.admin_atualizar_tipo_usuario(uuid,text)'::regprocedure)) > 0, 'proprietário não é atribuído pelo diretório de usuários');
select ok(position('v_barbeiro.funcao = ''proprietario''' in pg_get_functiondef('public.alterar_status_profissional(bigint,boolean)'::regprocedure)) > 0, 'proprietário ativo exige transferência antes da desativação');

select * from finish();
rollback;
